name: AI Docs Pipeline

on:
  push:
    paths:
      - 'logs/**'
      - 'scripts/**'
      - 'docs/generated/**'
      - 'mkdocs.yml'
      - '.github/workflows/**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install mkdocs mkdocs-material openai

    - name: Run log extraction
      run: python scripts/extract_logs.py

    - name: Run LLM generation
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      run: python scripts/gen_llm.py

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./site
